### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by juliandescottes**
Associated Bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1330779 
Try run : https://treeherder.mozilla.org/#/jobs?repo=try&revision=436d0a935e47b9528dafe53f3e9668869881eca1

### CODE REVIEW

**Comment by juliandescottes** [comment]
Let's use this PR to apply all the changes needed to get Bug 1330779 to land.
I will create a v0.1.0 tag after we merge it on master.

**Comment by juliandescottes** [comment]
cc @nchevobbe

**Comment by juliandescottes** [comment]
Thanks for the feedback @nchevobbe !

### Release process for Reps

A quick outline for releasing Reps (I like lists, sorry!)

```
1. Go to your clone of devtools-reps
  a. create a release branch on github
  b. update minor version in package.json, reset build version: 
    v0.N.X -> v0.N+1.0
  c. create a PR on Github for this release
  d. run /bin/publish-assets.js to create the bundle

2. Go to your clone of mozilla-central
  a. update mozilla-central to the latest
  b. copy : 
       assets/build/reps.js      -> devtools/shared/components/reps
       assets/build/reps.css     -> devtools/shared/components/reps
       assets/build/load-reps.js -> devtools/shared/components/reps
       assets/build/mochitest/*  -> devtools/shared/components/reps/test/mochitest/
  c. commit 'Bug XXXXXXX - reps v0.N+1.0: update devtools reps bundle from GitHub;r=reviewer'
  d. push to try, test locally, submit for review etc ...
  e. while try fails or some problem is detected, go back to devtools-reps, fix the issue, 
     create a new bundle and go back to 2.a
  f. when everything is fine and the patch is r+, land on autoland or inbound
  g. merge the PR on github
  h. create a tag on github

After that any issue with the bundle should be addressed with a new build version. 
Ideally, if the bundle has to be updated in mozilla-central for a bugfix, a corresponding
tag should be created on GitHub.

```

**Comment by nchevobbe** [comment]
Thanks for the writing @juliandescottes :)
Do you think we could put it in a RELEASE.md file in this repo ?
Also, I have the feeling we could automate some part of it with scripting/Circle, but for now that's a great first step.

**Comment by juliandescottes** [comment]
Done!

**Comment by juliandescottes** [comment]
Ok https://bugzilla.mozilla.org/show_bug.cgi?id=1330779 just landed on autoland, let's merge.

**Pull request merged**
